// Reads the local test cluster's catalog and emits a Database type.
// Run via scripts/gen-types.sh after changing a migration.
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const PGBIN = process.env.PGBIN ?? "/usr/lib/postgresql/16/bin";
const DB = process.env.DBNAME ?? "study_tracker_test";

function query(sql) {
  const isRoot = process.getuid?.() === 0;
  const args = ["-U", "postgres", "-d", DB, "-tAF", "|", "-c", sql];
  const out = isRoot
    ? execFileSync("su", [
        "postgres", "-s", "/bin/bash", "-c",
        `PGHOST=127.0.0.1 PGPORT=${process.env.PGPORT ?? 55432} ${PGBIN}/psql ` +
          args.map((a) => `'${a.replaceAll("'", "'\\''")}'`).join(" "),
      ])
    : execFileSync(`${PGBIN}/psql`, args, {
        env: { ...process.env, PGHOST: "127.0.0.1", PGPORT: process.env.PGPORT ?? "55432" },
      });
  return out.toString().trim().split("\n").filter(Boolean).map((l) => l.split("|"));
}

const SCALAR = {
  uuid: "string", text: "string", citext: "string", date: "string",
  "timestamp with time zone": "string", integer: "number", numeric: "number",
  boolean: "boolean", jsonb: "Json",
};

const enums = new Map();
for (const [name, label] of query(`
  select t.typname, e.enumlabel
  from pg_type t join pg_enum e on e.enumtypid = t.oid
  join pg_namespace n on n.oid = t.typnamespace
  where n.nspname = 'public' order by t.typname, e.enumsortorder`)) {
  if (!enums.has(name)) enums.set(name, []);
  enums.get(name).push(label);
}

const tsType = (pg) => SCALAR[pg] ?? (enums.has(pg) ? `Database["public"]["Enums"]["${pg}"]` : "unknown");

const tables = new Map();
for (const [table, col, type, notNull, hasDefault] of query(`
  select c.relname, a.attname, format_type(a.atttypid, a.atttypmod),
         a.attnotnull::text, (pg_get_expr(d.adbin, d.adrelid) is not null)::text
  from pg_class c
  join pg_namespace n on n.oid = c.relnamespace
  join pg_attribute a on a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped
  left join pg_attrdef d on d.adrelid = c.oid and d.adnum = a.attnum
  where n.nspname = 'public' and c.relkind = 'r'
  order by c.relname, a.attnum`)) {
  if (!tables.has(table)) tables.set(table, []);
  // Postgres renders a ::text cast of a boolean as "true"/"false", not "t"/"f".
  tables.get(table).push({
    col,
    type,
    nullable: notNull !== "true",
    optional: hasDefault === "true" || notNull !== "true",
  });
}

// Real foreign keys, so embedded selects such as
// subjects(name, color) infer their types instead of falling back to unknown.
const rels = new Map();
for (const [table, name, cols, refTable, refCols, unique] of query(`
  select c.conrelid::regclass::text,
         c.conname,
         (select string_agg(a.attname, ',' order by k.ord)
            from unnest(c.conkey) with ordinality k(attnum, ord)
            join pg_attribute a on a.attrelid = c.conrelid and a.attnum = k.attnum),
         c.confrelid::regclass::text,
         (select string_agg(a.attname, ',' order by k.ord)
            from unnest(c.confkey) with ordinality k(attnum, ord)
            join pg_attribute a on a.attrelid = c.confrelid and a.attnum = k.attnum),
         exists (
           select 1 from pg_index i
           where i.indrelid = c.conrelid and i.indisunique
             and i.indkey::int2[] @> c.conkey and c.conkey @> i.indkey::int2[]
         )::text
  from pg_constraint c
  join pg_namespace n on n.oid = c.connamespace
  where c.contype = 'f' and n.nspname = 'public'
  order by 1, 2`)) {
  const key = table.replace(/^public\./, "");
  if (!rels.has(key)) rels.set(key, []);
  rels.get(key).push({
    name,
    cols: cols.split(","),
    refTable: refTable.replace(/^public\./, ""),
    refCols: refCols.split(","),
    unique: unique === "true",
  });
}

const lines = [
  "// Generated by scripts/gen-types.sh from the live schema. Do not edit by hand.",
  "// Regenerate after any migration change.",
  "",
  "export type Json =",
  "  | string | number | boolean | null",
  "  | { [key: string]: Json | undefined }",
  "  | Json[];",
  "",
  "export type Database = {",
  "  public: {",
  "    Tables: {",
];

for (const [table, cols] of [...tables].sort()) {
  const row = cols.map((c) => `          ${c.col}: ${tsType(c.type)}${c.nullable ? " | null" : ""};`);
  const ins = cols.map((c) => `          ${c.col}${c.optional ? "?" : ""}: ${tsType(c.type)}${c.nullable ? " | null" : ""};`);
  const upd = cols.map((c) => `          ${c.col}?: ${tsType(c.type)}${c.nullable ? " | null" : ""};`);
  const relLines = (rels.get(table) ?? []).flatMap((r) => [
    "          {",
    `            foreignKeyName: "${r.name}";`,
    `            columns: [${r.cols.map((c) => `"${c}"`).join(", ")}];`,
    `            isOneToOne: ${r.unique};`,
    `            referencedRelation: "${r.refTable}";`,
    `            referencedColumns: [${r.refCols.map((c) => `"${c}"`).join(", ")}];`,
    "          },",
  ]);
  lines.push(
    `      ${table}: {`,
    "        Row: {", ...row, "        };",
    "        Insert: {", ...ins, "        };",
    "        Update: {", ...upd, "        };",
    relLines.length ? "        Relationships: [" : "        Relationships: [];",
    ...(relLines.length ? [...relLines, "        ];"] : []),
    "      };",
  );
}

lines.push("    };", "    Views: Record<string, never>;", "    Functions: {");

// Extension-owned functions (citext installs a great many into public) are
// excluded via pg_depend, and names are distinct because overloads collapse to
// one entry here.
const funcs = query(`
  select distinct p.proname
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and has_function_privilege('authenticated', p.oid, 'execute')
    and p.prokind = 'f'
    and pg_get_function_result(p.oid) <> 'trigger'
    and has_function_privilege('authenticated', p.oid, 'execute')
    and not exists (
      select 1 from pg_depend d
      where d.objid = p.oid and d.classid = 'pg_proc'::regclass and d.deptype = 'e'
    )
  order by p.proname`);

// Argument and return shapes are declared in lib/supabase/rpc.ts, which is
// hand-written because the useful shape of an RPC signature is a judgement
// call rather than a mechanical translation. This block only records which
// functions exist, so a renamed function breaks the build.
for (const [name] of funcs) {
  lines.push(`      ${name}: { Args: Record<string, unknown>; Returns: unknown };`);
}

lines.push("    };", "    Enums: {");
for (const [name, labels] of [...enums].sort()) {
  lines.push(`      ${name}: ${labels.map((l) => `"${l}"`).join(" | ")};`);
}
lines.push("    };", "    CompositeTypes: Record<string, never>;", "  };", "};", "");

writeFileSync(join(root, "lib/supabase/database.types.ts"), lines.join("\n"));
console.log("wrote lib/supabase/database.types.ts");
