// Generated by scripts/gen-types.sh from the live schema. Do not edit by hand.
// Regenerate after any migration change.

export type Json =
  | string | number | boolean | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      app_config: {
        Row: {
          key: string;
          value: number;
        };
        Insert: {
          key: string;
          value: number;
        };
        Update: {
          key?: string;
          value?: number;
        };
        Relationships: [];
      };
      friendships: {
        Row: {
          id: string;
          requester_id: string;
          addressee_id: string;
          status: Database["public"]["Enums"]["friendship_status"];
          created_at: string;
        };
        Insert: {
          id?: string;
          requester_id: string;
          addressee_id: string;
          status?: Database["public"]["Enums"]["friendship_status"];
          created_at?: string;
        };
        Update: {
          id?: string;
          requester_id?: string;
          addressee_id?: string;
          status?: Database["public"]["Enums"]["friendship_status"];
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "friendships_addressee_id_fkey";
            columns: ["addressee_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "friendships_requester_id_fkey";
            columns: ["requester_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      goals: {
        Row: {
          id: string;
          user_id: string;
          scope: Database["public"]["Enums"]["goal_scope"];
          subject_id: string | null;
          target_minutes: number;
          active_from: string;
          active_to: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          scope: Database["public"]["Enums"]["goal_scope"];
          subject_id?: string | null;
          target_minutes: number;
          active_from?: string;
          active_to?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          scope?: Database["public"]["Enums"]["goal_scope"];
          subject_id?: string | null;
          target_minutes?: number;
          active_from?: string;
          active_to?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "goals_subject_id_fkey";
            columns: ["subject_id"];
            isOneToOne: false;
            referencedRelation: "subjects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "goals_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      points_ledger: {
        Row: {
          id: string;
          user_id: string;
          delta: number;
          reason: Database["public"]["Enums"]["ledger_reason"];
          session_id: string | null;
          redemption_id: string | null;
          awarded_for_date: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          delta: number;
          reason: Database["public"]["Enums"]["ledger_reason"];
          session_id?: string | null;
          redemption_id?: string | null;
          awarded_for_date?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          delta?: number;
          reason?: Database["public"]["Enums"]["ledger_reason"];
          session_id?: string | null;
          redemption_id?: string | null;
          awarded_for_date?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "points_ledger_redemption_id_fkey";
            columns: ["redemption_id"];
            isOneToOne: false;
            referencedRelation: "redemptions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "points_ledger_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: true;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "points_ledger_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          handle: string;
          display_name: string;
          timezone: string;
          daily_goal_minutes: number;
          hide_subjects_from_friends: boolean;
          pomodoro_work_minutes: number;
          pomodoro_break_minutes: number;
          pomodoro_long_break_minutes: number;
          pomodoro_rounds_before_long_break: number;
          created_at: string;
        };
        Insert: {
          id: string;
          handle: string;
          display_name: string;
          timezone?: string;
          daily_goal_minutes?: number;
          hide_subjects_from_friends?: boolean;
          pomodoro_work_minutes?: number;
          pomodoro_break_minutes?: number;
          pomodoro_long_break_minutes?: number;
          pomodoro_rounds_before_long_break?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          handle?: string;
          display_name?: string;
          timezone?: string;
          daily_goal_minutes?: number;
          hide_subjects_from_friends?: boolean;
          pomodoro_work_minutes?: number;
          pomodoro_break_minutes?: number;
          pomodoro_long_break_minutes?: number;
          pomodoro_rounds_before_long_break?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey";
            columns: ["id"];
            isOneToOne: true;
            referencedRelation: "auth.users";
            referencedColumns: ["id"];
          },
        ];
      };
      redemptions: {
        Row: {
          id: string;
          user_id: string;
          reward_id: string;
          points_spent: number;
          redeemed_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          reward_id: string;
          points_spent: number;
          redeemed_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          reward_id?: string;
          points_spent?: number;
          redeemed_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "redemptions_reward_id_fkey";
            columns: ["reward_id"];
            isOneToOne: false;
            referencedRelation: "rewards";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "redemptions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      rewards: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          cost_points: number;
          cooldown_hours: number | null;
          archived_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          cost_points: number;
          cooldown_hours?: number | null;
          archived_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          cost_points?: number;
          cooldown_hours?: number | null;
          archived_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "rewards_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      session_pauses: {
        Row: {
          id: string;
          session_id: string;
          paused_at: string;
          resumed_at: string | null;
        };
        Insert: {
          id?: string;
          session_id: string;
          paused_at?: string;
          resumed_at?: string | null;
        };
        Update: {
          id?: string;
          session_id?: string;
          paused_at?: string;
          resumed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "session_pauses_session_id_fkey";
            columns: ["session_id"];
            isOneToOne: true;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
        ];
      };
      sessions: {
        Row: {
          id: string;
          user_id: string;
          subject_id: string;
          subtopic_id: string | null;
          mode: Database["public"]["Enums"]["session_mode"];
          status: Database["public"]["Enums"]["session_status"];
          started_at: string;
          ended_at: string | null;
          planned_seconds: number | null;
          net_seconds: number | null;
          note: string | null;
          is_manual: boolean;
          auto_closed: boolean;
          chained_from_session_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          subject_id: string;
          subtopic_id?: string | null;
          mode?: Database["public"]["Enums"]["session_mode"];
          status?: Database["public"]["Enums"]["session_status"];
          started_at?: string;
          ended_at?: string | null;
          planned_seconds?: number | null;
          net_seconds?: number | null;
          note?: string | null;
          is_manual?: boolean;
          auto_closed?: boolean;
          chained_from_session_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          subject_id?: string;
          subtopic_id?: string | null;
          mode?: Database["public"]["Enums"]["session_mode"];
          status?: Database["public"]["Enums"]["session_status"];
          started_at?: string;
          ended_at?: string | null;
          planned_seconds?: number | null;
          net_seconds?: number | null;
          note?: string | null;
          is_manual?: boolean;
          auto_closed?: boolean;
          chained_from_session_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "sessions_chained_from_session_id_fkey";
            columns: ["chained_from_session_id"];
            isOneToOne: false;
            referencedRelation: "sessions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sessions_subject_id_fkey";
            columns: ["subject_id"];
            isOneToOne: false;
            referencedRelation: "subjects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sessions_subtopic_id_fkey";
            columns: ["subtopic_id"];
            isOneToOne: false;
            referencedRelation: "subtopics";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sessions_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      subjects: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          color: string;
          sort_order: number;
          archived_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          color: string;
          sort_order?: number;
          archived_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          color?: string;
          sort_order?: number;
          archived_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subjects_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      subtopics: {
        Row: {
          id: string;
          subject_id: string;
          name: string;
          sort_order: number;
          archived_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          subject_id: string;
          name: string;
          sort_order?: number;
          archived_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          subject_id?: string;
          name?: string;
          sort_order?: number;
          archived_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subtopics_subject_id_fkey";
            columns: ["subject_id"];
            isOneToOne: false;
            referencedRelation: "subjects";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: {
      active_ranges: { Args: Record<string, unknown>; Returns: unknown };
      active_seconds: { Args: Record<string, unknown>; Returns: unknown };
      active_session: { Args: Record<string, unknown>; Returns: unknown };
      active_slices: { Args: Record<string, unknown>; Returns: unknown };
      add_manual_session: { Args: Record<string, unknown>; Returns: unknown };
      are_friends: { Args: Record<string, unknown>; Returns: unknown };
      block_user: { Args: Record<string, unknown>; Returns: unknown };
      cfg: { Args: Record<string, unknown>; Returns: unknown };
      clear_goal: { Args: Record<string, unknown>; Returns: unknown };
      complete_onboarding: { Args: Record<string, unknown>; Returns: unknown };
      complete_session: { Args: Record<string, unknown>; Returns: unknown };
      current_streak: { Args: Record<string, unknown>; Returns: unknown };
      daily_goal_met_on: { Args: Record<string, unknown>; Returns: unknown };
      discard_session: { Args: Record<string, unknown>; Returns: unknown };
      finalize_stale_sessions: { Args: Record<string, unknown>; Returns: unknown };
      find_profile_by_handle: { Args: Record<string, unknown>; Returns: unknown };
      friend_activity: { Args: Record<string, unknown>; Returns: unknown };
      friend_leaderboard: { Args: Record<string, unknown>; Returns: unknown };
      goal_status: { Args: Record<string, unknown>; Returns: unknown };
      is_valid_timezone: { Args: Record<string, unknown>; Returns: unknown };
      pause_session: { Args: Record<string, unknown>; Returns: unknown };
      pending_friend_requests: { Args: Record<string, unknown>; Returns: unknown };
      point_balance: { Args: Record<string, unknown>; Returns: unknown };
      redeem_reward: { Args: Record<string, unknown>; Returns: unknown };
      remove_friend: { Args: Record<string, unknown>; Returns: unknown };
      respond_to_friend_request: { Args: Record<string, unknown>; Returns: unknown };
      resume_session: { Args: Record<string, unknown>; Returns: unknown };
      reward_status: { Args: Record<string, unknown>; Returns: unknown };
      send_friend_request: { Args: Record<string, unknown>; Returns: unknown };
      server_now: { Args: Record<string, unknown>; Returns: unknown };
      session_effective_end: { Args: Record<string, unknown>; Returns: unknown };
      session_pause_ranges: { Args: Record<string, unknown>; Returns: unknown };
      set_goal: { Args: Record<string, unknown>; Returns: unknown };
      start_session: { Args: Record<string, unknown>; Returns: unknown };
      suggest_handle: { Args: Record<string, unknown>; Returns: unknown };
      switch_session_subject: { Args: Record<string, unknown>; Returns: unknown };
      today_seconds: { Args: Record<string, unknown>; Returns: unknown };
      undo_discard_session: { Args: Record<string, unknown>; Returns: unknown };
      user_day_seconds: { Args: Record<string, unknown>; Returns: unknown };
      user_day_subject_seconds: { Args: Record<string, unknown>; Returns: unknown };
      user_today: { Args: Record<string, unknown>; Returns: unknown };
      user_total_seconds: { Args: Record<string, unknown>; Returns: unknown };
    };
    Enums: {
      friendship_status: "pending" | "accepted" | "blocked";
      goal_scope: "daily" | "weekly";
      ledger_reason: "session" | "goal_bonus" | "streak_bonus" | "redemption" | "adjustment";
      session_mode: "stopwatch" | "pomodoro";
      session_status: "running" | "paused" | "completed" | "discarded";
    };
    CompositeTypes: Record<string, never>;
  };
};
